#!/usr/bin/env python3
"""Generate .SRCINFO from PKGBUILD.

The file is generated, never committed (see ../../.gitignore), and is meant
for `pkgctl`/AUR publishing.  Run it from the directory that contains the
PKGBUILD:

    python3 gen_srcinfo.py

This mirrors packages/aur/gen_srcinfo.py in the dev-sidecar project: it is
used when AUR publishing runs on a machine without makepkg (e.g. CI).

NOTE: the checked-in PKGBUILD builds from a *local* source tarball for day to
day development, so the generated .SRCINFO is only useful after `source` has
been pointed at a remote (GitHub) archive.
"""
from __future__ import annotations

import pathlib
import re
import sys

pkgbuild = pathlib.Path("PKGBUILD").read_text(encoding="utf-8")


def scalar(var: str, default: str = "") -> str:
    m = re.search(rf"^{var}=(.*)$", pkgbuild, re.MULTILINE)
    if not m:
        return default
    return m.group(1).strip().strip("'\"")


def array(var: str) -> list[str]:
    """Parse `var=(...)`, including multi-line arrays."""
    m = re.search(rf"^{var}=\((.*?)\)", pkgbuild, re.MULTILINE | re.DOTALL)
    if not m:
        return []
    body = re.sub(r"#.*", "", m.group(1))
    return re.findall(r"['\"]([^'\"]+)['\"]", body)


def expand(value: str) -> str:
    """Expand the handful of shell variables PKGBUILDs commonly use."""
    for name in ("pkgname", "pkgver", "pkgrel", "pkgbase"):
        value = value.replace(f"${{{name}}}", globals().get(name, ""))
        value = value.replace(f"${name}", globals().get(name, ""))
    return value


def arch_arrays(prefix: str) -> list[tuple[str, list[str]]]:
    out = []
    for m in re.finditer(rf"^{prefix}_([a-z0-9_]+)=\((.*?)\)", pkgbuild,
                         re.MULTILINE | re.DOTALL):
        body = re.sub(r"#.*", "", m.group(2))
        vals = re.findall(r"['\"]([^'\"]+)['\"]", body)
        out.append((m.group(1), vals))
    return out


pkgname = scalar("pkgname")
pkgver = scalar("pkgver")
pkgrel = scalar("pkgrel")
pkgdesc = scalar("pkgdesc")
url = scalar("url")
archs = array("arch")
license_ = array("license")
depends = array("depends")
optdepends = array("optdepends")
makedepends = array("makedepends")
provides = array("provides")
conflicts = array("conflicts")
replaces = array("replaces")

if not pkgname:
    sys.exit("gen_srcinfo.py: no pkgname in PKGBUILD")

lines: list[str] = []
lines.append("# Generated by gen_srcinfo.py")
lines.append(f"pkgbase = {pkgname}")
lines.append(f"\tpkgdesc = {pkgdesc}")
lines.append(f"\tpkgver = {pkgver}")
lines.append(f"\tpkgrel = {pkgrel}")
lines.append(f"\turl = {url}")
for a in archs:
    lines.append(f"\tarch = {a}")
for lic in license_:
    lines.append(f"\tlicense = {lic}")
for d in makedepends:
    lines.append(f"\tmakedepends = {d}")
for d in depends:
    lines.append(f"\tdepends = {d}")
for d in optdepends:
    lines.append(f"\toptdepends = {d}")
for p in provides:
    lines.append(f"\tprovides = {p}")
for c in conflicts:
    lines.append(f"\tconflicts = {c}")
for r in replaces:
    lines.append(f"\treplaces = {r}")

# Architecture-specific sources take priority over a plain `source`.
arch_sources = dict(arch_arrays("source"))
arch_sums = dict(arch_arrays("sha256sums"))
if arch_sources:
    for a, srcs in arch_sources.items():
        for s in srcs:
            lines.append(f"\tsource_{a} = {expand(s)}")
        for s in arch_sums.get(a, []):
            lines.append(f"\tsha256sums_{a} = {expand(s)}")
else:
    for s in array("source"):
        lines.append(f"\tsource = {expand(s)}")
    for s in array("sha256sums"):
        lines.append(f"\tsha256sums = {expand(s)}")

lines.append("")
lines.append(f"pkgname = {pkgname}")

pathlib.Path(".SRCINFO").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(".SRCINFO generated:\n" + "\n".join(lines))
